on: 
  workflow_dispatch:
  
name: Deploy Infra

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: developing
    env:
      ResourceGroupName: carsonazure-rg
      ResourceGroupLocation: "westeurope"
      DeploymentName: carsonazure-dn
      BicepFileLocation: '**/Deploy/Main.Bicep'
      BicepFileParametersLocation: '**/Deploy/main.parameters.json'
    steps:
    - uses: actions/checkout@master

    - uses: azure/login@v1
      name: Login
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - uses: Azure/CLI@v1
      name: Create ResourceGroup
      with:
        inlineScript: |
          #!/bin/bash
          az group create --name ${{ env.ResourceGroupName }} --location ${{ env.ResourceGroupLocation }}
          echo "Azure resource group created"
          
    - uses: Azure/CLI@v1
      name: Create Environment
      with:
        inlineScript: |
          #!/bin/bash
           az deployment group create \
              --name ${{ env.DeploymentName }} \
              --resource-group ${{ env.ResourceGroupName }} \
              --template-file ${{ env.BicepFileLocation }} \
              --parameters @${{ env.BicepFileParametersLocation }}
        
       
