on: 
  workflow_dispatch:
  
name: Deploy Infra

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      ResourceGroupName: carsonazure-rg
      ResourceGroupLocation: "westeurope"
      DeploymentName: carsonazure-dn
      BicepFileLocation: ../../Deploy/Main.Bicep
      BicepFileParametersLocation: ../../Deploy/main.parameters.json
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        environment: development
    - uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          az group create --name ${{ env.ResourceGroupName }} --location ${{ env.ResourceGroupLocation }}
          echo "Azure resource group created"
    - uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
           az deployment group create `
              --name #{{ env.DeploymentName }} `
              --resource-group #{{ env.ResourceGroupName }} `
              --template-file #{{ env.BicepFileLocation }} `
              --TemplateParameterFile #{{ env.BicepFileParametersLocation }}
        
       
